### ISSUE TITLE
数据库有密码要怎么配置

### ISSUE THREAD

**Issue by maojinhua** [momosecurity/aswan#16]
mysql数据库有密码 我改了config下的devlop.py,product.py,test.py的mysql密码但还是报错
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

**Comment by maojinhua** [comment]
找到了 在settings/local_settings。。。。。
为啥要分开- -

**Comment by leohowell** [comment]
@maojinhua 分为本地配置和线上配置，本地配置方便本地调试

**Comment by Flynnon** [comment]
这个主要是为了区别 `服务` 和 `后台`部分的依赖，避免他们混在一起。

**Comment by maojinhua** [comment]
嗯 好的谢谢
