### ISSUE TITLE
拦截日志无记录

### ISSUE THREAD

**Issue by xtomatoziyang** [momosecurity/aswan#17]
`curl 127.0.0.1:50000/query/ -X POST -d '{"rule_id": "2", "user_id": "10086", "ip": "127.0.0.1"}' -H "Content-Type:application/json"`

`{"result": {"control": "deny", "weight": 101}, "ec": 0}%    `

**Comment by Flynnon** [comment]
请按照下面的方式检查一下：
1. 看下是否执行了 python manage.py persistence_hit_log 这个命令；
2. 看下`aswan/www`目录下是否有 nohup.out 文件，如果有的话，看下是否出现了与 #15 一样的问题；
3. 如果都没有的话，看下 `risk_control` 中是否有匹配 `hit_log_*` 模式的表，并看下表中是否有数据。

有详细信息麻烦再次贴出来，感谢。
