### ISSUE TITLE
你好 请问未来会支持更加丰富的规则和数据源吗

### ISSUE THREAD

**Issue by maojinhua** [momosecurity/aswan#18]
看了源码,之前的功能只能是在每次report上报的时候对redis的计数器加一，然后匹配次数。也就是不能加一些具体的数值,比如说我想统计一个玩家对游戏在某个时间段内的充值金额,目前就无法满足.

**Comment by Flynnon** [comment]
首先有一个问题，这个功能真的需要在风控系统里实现么?
实现方面，可以自定义一个 Source，类似[限用户数型数据源](https://github.com/momosecurity/aswan/blob/063729e99676da25623fd51bfdea73172f71c59e/risk_models/source.py#L153)来专门存储此类信息，只需重写 get_member 和 check_member 即可。
