### ISSUE TITLE
拦截日志不显示，数据库有数据，hit_log_20190729这个表和og_manage_hitlogmodel关系是什么，没有查到这个带日期的表

### ISSUE THREAD

**Issue by cylin0108** [momosecurity/aswan#19]

**Comment by Flynnon** [comment]
### 设计
为了性能考虑，aswan系统的日志是先写到redis中，在由另外的进程进行消费及持久化(存储到mysql中)，另外由于MOMO风控系统的请求量很大，因此在拦截日志持久化的时候进行了按天分表。

### 代码
[记录拦截日志](
https://github.com/momosecurity/aswan/blob/063729e99676da25623fd51bfdea73172f71c59e/risk_models/rule.py#L250)
[消费日志](https://github.com/momosecurity/aswan/blob/063729e99676da25623fd51bfdea73172f71c59e/www/log_manage/management/commands/persistence_hit_log.py#L88)
[具体的分表写入部分](https://github.com/momosecurity/aswan/blob/063729e99676da25623fd51bfdea73172f71c59e/www/log_manage/management/commands/persistence_hit_log.py#L57)

### 问题解释
aswan系统分表时使用的模式如下
``` python
table_name = f"hit_log_{date_obj.strftime('%Y%m%d')}"
```
很容易理解，hit_log_20190729 存储2019年7月29日的拦截日志。
log_manage_hitlogmodel表则是在升级python3后，建表错误导致的非预期的表，具体修复PR可见 #20 。

**Comment by cylin0108** [comment]
log_manage_hitlogmodel表则是在升级python3后，建表错误导致的非预期的表，这个修复方案什么时候给说下

**Comment by Flynnon** [comment]
已经修复了，目前已经不会在生成这个表了，PR 可见 #20 。
