### ISSUE TITLE
上报数据后redis key的数量会增加，是否设置过期时间，设置多久，基本策略的key是否会过期

### ISSUE THREAD

**Issue by cylin0108** [momosecurity/aswan#21]

**Comment by Flynnon** [comment]
这里直接看代码吧， [上报数据写入逻辑](https://github.com/momosecurity/aswan/blob/063729e99676da25623fd51bfdea73172f71c59e/risk_models/source.py#L225)。

另外，基本策略的key是指哪些呢?
