### ISSUE TITLE
如何处理高并发的上报，启动risk_server.py 脚本后，上报数据过多，处理不过来，报错

### ISSUE THREAD

**Issue by cylin0108** [momosecurity/aswan#25]

**Comment by Flynnon** [comment]
可以考虑如下几个方面：
1. 水平扩展，多部署几个服务，前面使用Nginx进行反向代理，将流量分发给后端(简单的轮询策略即可)；
2. 读写分离，可以将 report 和 query 接口分离，分别部署，便于针对性扩容；
3. 使用更加高效的server服务器，例如 gunicorn 。

**Comment by oldman1991** [comment]
具体的报的什么错可以贴一下出来么
