### ISSUE TITLE
当有大量query操作的时候，会出现{"error": "rule_id does not exist or is offline", "ec": 101} ，单独测试没有问题，请问redis有特殊设置后者rule有特殊设置

### ISSUE THREAD

**Issue by cylin0108** [momosecurity/aswan#26]

**Comment by Flynnon** [comment]
这个是之前的一个bug导致的，已修复。
详见：https://github.com/momosecurity/aswan/pull/35/files/ef88dc6ba726e7024b1e9ce1a1cd744f33d2c908#r341496292
