### ISSUE TITLE
服务器上安装后无法远程访问

### ISSUE THREAD

**Issue by happyhiroc** [momosecurity/aswan#3]
启动成功后，本地可以127.0.0.1:8000访问系统，
但远程服务器上安装后 按照 http://serverIp:8000/方式无法访问（防火墙已开放8000端口），
对start.sh中 #使用uwsgi启动后台 中127.0.0.1:8000改为0.0.0.0:8000 也不行

**Comment by huohuohahei** [comment]
改为本地ip试试

**Comment by Flynnon** [comment]
建议看下uwsgi的[文档](https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html)。

而具体到这个问题，有如下两种临时解决方案(均不可用于线上)：
1. 使用django自带的runserver命令
```  bash
python ${cur_dir}/www/manage.py runserver 0.0.0.0:8000
```
2. 使用uwsgi的http模式
``` bash
uwsgi --master --vacuum --processes 10 --http :8000 --chdir ${cur_dir}/www --max-requests 5000 --module wsgi:application --logto ${cur_dir}/www/risk-control.log --pidfile ${cur_dir}/www/risk-control.pid
```
