### ISSUE TITLE
strategy重定向的路由是不是配置的有问题？

### ISSUE THREAD

**Issue by wangjinyu124419** [momosecurity/aswan#31]
`    url(r'^$',
        RedirectView.as_view(url=reverse_lazy("strategy:strategy_list"),
                             permanent=True), name="strategy_index"),`
报错：
`Reverse for 'strategy_list' not found. 'strategy_list' is not a valid view function or pattern name`
这段代码是想重定向到menu_strategy/list吧？
原本是想写成
`    url(r'^$',
        RedirectView.as_view(url=reverse_lazy("strategy:menu_strategy_list"),
                             permanent=True), name="strategy_index"),`
这样吗？

**Comment by Flynnon** [comment]
嗯，是这样的，后续会改一下。
#### 之前没有测到这里，十分感谢~
