### ISSUE TITLE
KeyError: 'user_id'导致拦截日志持久化进程异常终止

### ISSUE THREAD

**Issue by wismartzy** [momosecurity/aswan#36]
在不需要上报user_id字段情况下触发并命中策略后，持久化进程将会异常终止，后续拦截日志无法显示，查看nohup.out报错如下：
`  ...
File "/xxx/xxx/aswan/www/log_manage/management/commands/persistence_hit_log.py", line 33, in parse_msg
    d['user_id'] = req_body['user_id']
KeyError: 'user_id'`

命中的策略规则：时段频控型策略
策略详情：相同ip，在最近30s内，限10次(xxx数据源)
查询的数据：`{'rule_id': 2, 'ip': ip}`

`/xxx/xxx/aswan/www/log_manage/management/commands/persistence_hit_log.py` 33行修改为`d['user_id'] = req_body.get('user_id', '')`得到解决。

**Comment by leohowell** [comment]
Thanks! 我们确认一下问题，然后尽快修复。

**Comment by leohowell** [comment]
@wismartzy 此问题确认！太棒了！👍 
有兴趣提交一个Pull Request来修复此问题吗？ 期待回复。

**Comment by wismartzy** [comment]
好的
