### ISSUE TITLE
规则配置内 strategy_index 为 0 的情况阈值将无法修改

### ISSUE THREAD

**Issue by wismartzy** [momosecurity/aswan#38]
https://github.com/momosecurity/aswan/blob/e42ade1d82e3570c7b8246d148f32fa4f3573946/www/rule/views.py#L395

从参数中获取需要修改的策略组的下标（strategy_index）为0的情况下触发assert断言，导致修改阈值会失败。

影响范围：
规则配置 - 详情 - 编辑阈值
影响规则内第一条阈值型策略的阈值修改

**Comment by leohowell** [comment]
👍  我们确认下问题，后面安排修复。

**Comment by leohowell** [comment]
问题确认！太棒了！请问有兴趣提PR吗？如果您没有时间的话，我们将在24小时内安排修复此问题。

**Comment by leohowell** [comment]
> 问题确认！太棒了！请问有兴趣提PR吗？如果您没有时间的话，我们将在24小时内安排修复此问题。

考虑到这个改动较大，我们已安排了修复。如您已在编写PR, 实在抱歉。

https://github.com/momosecurity/aswan/pull/39

欢迎review
