### ISSUE TITLE
请问如何自动维护黑名单？

### ISSUE THREAD

**Issue by dbdoer** [momosecurity/aswan#43]
比如对于恶意访问用户，如何能及时的将这批ip或者设备号加入到黑名单中，以便防住攻击呢？目前好像是手动添加黑名单记录？

**Comment by Flynnon** [comment]
这个实现的方式有很多。
如果数据产出方是风控系统的话，可以直接写脚本更新DB(需要包括mongo和redis)。
如果想解耦的话，可以增加一个名单变更的接口，接收名单变更请求，然后将请求扔到队列里，由后端脚本消费更新。
