### ISSUE TITLE
运行不了， Address already in use: ('127.0.0.1', 50000)

### ISSUE THREAD

**Issue by luozhili1999** [momosecurity/aswan#5]
**输出错误：**
![image](https://user-images.githubusercontent.com/39750120/59731070-6123a400-9277-11e9-95d0-1faba93ac89d.png)

**杀过占用端口的进程了**
![image](https://user-images.githubusercontent.com/39750120/59731277-0a6a9a00-9278-11e9-87b1-6a11190dacfe.png)

**任然运行不了**

**Comment by luozhili1999** [comment]
执行到这一步时出现的问题
Python 版本  2.7.15+
![image](https://user-images.githubusercontent.com/39750120/59731335-3c7bfc00-9278-11e9-9ac4-36a83a96a319.png)

**Comment by Flynnon** [comment]
1. 目前 start.sh 会采用nohup的方式启动三种服务，因此需要看下是否重复启动了；
2. 目前端口号配置项为 `aswan/config/base.py` 中的 `RISK_SERVER_PORT` 项，可以修改端口号试试是否可以启动。
