### ISSUE TITLE
有沟通微信群吗？

### ISSUE THREAD

**Issue by kinghuzhuoyi** [momosecurity/aswan#50]
我在做互金信贷业务和支付业务的风控系统，希望能够一起沟通交流下

我个人WX：
![image](https://user-images.githubusercontent.com/2224714/74585500-3b25ed80-5018-11ea-9a63-3ecb97d3d2f9.png)

**Comment by Flynnon** [comment]
目前没有精力维护一个微信群，有什么问题的话，可以提issue或者发邮件来沟通~

**Comment by kinghuzhuoyi** [comment]
风控系统里面的特征有使用到流处理吗？

**Comment by leohowell** [comment]
我们使用了flink来处理各类请求日志、行为日志，如通过复杂模式匹配（CEP）检查用户行为关键路径是否缺失，产出的结果作为一个数据源输入到风控系统中。flink处理的逻辑属于产出和分析异常的部分，不在目前开源的风控的策略和管控逻辑中。流处理和风控系统配合使用时没有什么问题的。

**Comment by leohowell** [comment]
如果您需要进行即时的交流沟通，请跟我发一封邮件(我主页有邮箱)，我们交换一下联系方式，谢谢
