### ISSUE TITLE
模板嵌套之后值拿不到

### ISSUE THREAD

**Issue by yujieyzjh** [momosecurity/aswan#52]
在模板：aswan/www/templates/pagination.html里只能获取到
{% render_table table "table.html" %}之后的table的值

其余值获取不到   分页显示有问题
![image](https://user-images.githubusercontent.com/25274214/75665658-7890a900-5caf-11ea-9aec-e1cae14fa277.png)
![image](https://user-images.githubusercontent.com/25274214/75665723-9231f080-5caf-11ea-9b9c-ded87d2d744d.png)

**Comment by Flynnon** [comment]
可以看下该view的enable_page_size_config是否设置为True

**Comment by Flynnon** [comment]
可以看下  aswan/www/core/generic.py  这里

**Comment by yujieyzjh** [comment]
enable_page_size_config 设置了的  现在我的解决方法是在      {% render_table table "table.html" %}

之后  加入
{% block pagination %}
                {% include "pagination.html" %}
{% endblock %}

![image](https://user-images.githubusercontent.com/25274214/75945022-1795ea80-5ed4-11ea-9594-7eab41a682ab.png)
