### ISSUE TITLE
source的处理逻辑似乎有点问题

### ISSUE THREAD

**Issue by pysenic** [momosecurity/aswan#54]
report.py里面验证请求的body是否和设置的数据源一致

Sources类中有：
    def check_all(self, name, data):
        sources = self.get_source_or_raise(name)
        return all([source.check_all(data) for source in sources])

该方法验证不通过

    def load_sources(self):
        name_sources_map = defaultdict(set)
        RawSource.load_raw_source()
        raw_name_source_map_lst = []
        try:
            for source_cls in _used_source_cls_set:
                raw_name_source_map_lst.append(source_cls.load())
        except redis.RedisError:
            return
        else:
            for raw_name_sources_map in raw_name_source_map_lst:
                for name, sources in raw_name_sources_map.items():
                    name_sources_map[name] |= sources
            self.name_sources_map = name_sources_map

这里load_raw_source了redis中定义的数据源，但是没有放到name_sources_map中

**Comment by Flynnon** [comment]
[将raw_source与具体的Source绑定](https://github.com/momosecurity/aswan/blob/7e43f1a7e87c3aa09d710dc64316ad63c90c9115/risk_models/source.py#L176)
[在source中必须的key及对应类型](
https://github.com/momosecurity/aswan/blob/7e43f1a7e87c3aa09d710dc64316ad63c90c9115/risk_models/source.py#L68)
[校验类型](https://github.com/momosecurity/aswan/blob/7e43f1a7e87c3aa09d710dc64316ad63c90c9115/risk_models/source.py#L105)

**Comment by pysenic** [comment]
感谢回复！
[这附近只注册了现在用户型和时频型2种数据源](https://github.com/momosecurity/aswan/blob/7e43f1a7e87c3aa09d710dc64316ad63c90c9115/risk_models/source.py#L147)

并且还必须是已经存在基于souce的策略，这里为什么要这么处理呢？

**Comment by pysenic** [comment]
数据源的处理逻辑是不是这样：
1. 页面定义了数据源存到了redis，可以用register_source_cls读出来
2. 每次上报，不要求必传数据源定义中的所有key，但是策略里面用到了的，就必须要上传
3. 策略里面用到又分了4个类型，但是代码里只写了其中2个

**Comment by Flynnon** [comment]
1. 不是，register_source_cls 这个方法的引用仅仅是方便管理，以统一进行策略的配置刷新等等；
2. 是的，这里的校验是按需的，只有被策略引用的key才会被校验；
3. 目前有四种已实现的策略，其中仅有限用户数型和时段频控型才需要业务方的上报数据，因此只有这两个策略对应了Source。

**Comment by Flynnon** [comment]
> 数据源的处理逻辑是不是这样：
> 
> 1. 页面定义了数据源存到了redis，可以用register_source_cls读出来
> 2. 每次上报，不要求必传数据源定义中的所有key，但是策略里面用到了的，就必须要上传
> 3. 策略里面用到又分了4个类型，但是代码里只写了其中2个

1. 不是，register_source_cls 这个方法的引用仅仅是方便管理，以统一进行策略的配置刷新等等；
2. 是的，这里的校验是按需的，只有被策略引用的key才会被校验；
3. 目前有四种已实现的策略，其中仅有限用户数型和时段频控型才需要业务方的上报数据，因此只有这两个策略对应了Source。

**Comment by Flynnon** [comment]
> 感谢回复！
> [这附近只注册了现在用户型和时频型2种数据源](https://github.com/momosecurity/aswan/blob/7e43f1a7e87c3aa09d710dc64316ad63c90c9115/risk_models/source.py#L147)
> 
> 并且还必须是已经存在基于souce的策略，这里为什么要这么处理呢？

这里的关系搞反了，不是先存在source，然后有了对应的策略。Source是某一种特定的数据校验、存储、读取方式的封装/抽象，是为了特定的策略服务的。当新增一种策略(例如: 前置性策略，用户是前x秒内有过上报)时，只有此策略的运算需要依赖业务方的上报数据，才会抽象出特定的Source来对上报数据进行组织。
已有的四种策略中，bool型与名单型的运算不需要依赖业务方的上报，因此此处就没有关联的Source。

**Comment by pysenic** [comment]
我是带着我们的业务场景来思考的，看代码的时候很困惑，听了你的解释豁然开朗。
今天把risk_server相关的代码看完了，设计的非常棒，很多地方处理的非常巧妙。
我本身是做大数据的，只写过BI系统的后端服务，看完代码以后收益匪浅，非常棒的开源项目，感谢开源！

**Comment by pysenic** [comment]
我应该会把risk_server抽出来写成单独的服务，这部分会借鉴你们的设计思想和代码，请不要介意
然后再有一个前后端分离的管理页面
最后会把流计算接进来，现在这个计算压力都在服务本身和redis

**Comment by npc7** [comment]
> 我应该会把risk_server抽出来写成单独的服务，这部分会借鉴你们的设计思想和代码，请不要介意
> 然后再有一个前后端分离的管理页面
> 最后会把流计算接进来，现在这个计算压力都在服务本身和redis

在风控策略原子上，aswan是不全面的，只是针对momo的场景，或者开源的是阉割版
比如：
1.名单是强绑定的，正常的应该是自定义名单，在配置策略是可以选择对应上
2.缺少时间段规则
3.只有A条件下userid的频控，实际情况需要的是在A条件下B的频控  
4.配置规则如果可以结合yaml 会更棒

risk_server 部分既需要api接入线上数据，也需要考虑离线数据，你的很多规则是需要使用历史的离线数据进行回测的

既然哥们准备改造，以上皆为建议
