### ISSUE TITLE
请问首次命中规则之后，再次请求query接口。接口还是返回被风控，这种怎么处理?

### ISSUE THREAD

**Issue by ahwangxiang1994** [momosecurity/aswan#56]
请问首次命中规则之后，再次请求query接口。接口还是返回被风控，这种怎么处理?

**Comment by Flynnon** [comment]
这种是正常结果
您这边的背景是什么，希望能达到怎样的效果呢?

**Comment by ahwangxiang1994** [comment]
> 这种是正常结果
> 您这边的使用场景是什么，希望能达到怎样的效果呢?

我们的管理后台有删除用户的功能。假设一个管理员进入系统删除用户，当他连续(一个周期内，比如一分钟内)删除了三个用户之后我希望他再次删人时需要他的手机号接收一个验证码才能继续删除。当输入完验证码通过之后，这个规则在一天内对他就不生效了，不然每次删人都要输入验证码。

**Comment by Flynnon** [comment]
这种逻辑我们目前是放在业务侧的，即风控针对某种行为要返回什么样的结果(此处是message)，然后由业务侧触发短信验证。在达到此种豁免条件(比如手机号认证/实名认证)后，由业务侧来保存这个结果，然后豁免(即不再请求风控)。
如果希望在风控侧做这个功能的话，可以在业务侧推送/风控主动获取认证结果后，将这个用户加到某个白名单里(有效期设置为一天)实现。

**Comment by Flynnon** [comment]
也可以由业务侧提供一个获取最近一次短信验证时间的接口，然后开发一个策略原子实现~

**Comment by ahwangxiang1994** [comment]
> 为了简单，目前这种逻辑我们是放在业务侧实现的，即风控只针对某次行为返回对应的管控原子(此处会返回message)，控制业务侧下一步的行为(此处为开启短信验证)。而在用户满足此种条件后(比如手机号认证/实名认证)，由业务侧来保存这个结果，然后直接放行(即不再请求风控)。
> 如果希望在风控侧做这个功能的话，可以在业务侧推送/其余地方回调拿到认证结果后，将这个用户加到某个白名单里(有效期设置为一天)实现。

加白名单的话貌似是需要操作风控的数据库吧，没有直接加白名单的接口

**Comment by Flynnon** [comment]
嗯，目前没有。
可以仿照录入名单那里开发一个接口/对应功能。
欢迎提MR~
