### ISSUE TITLE
why you guys use two databases ? is it necessary to use MySQL for storing rule-hit-log ?

### ISSUE THREAD

**Issue by no7dw** [momosecurity/aswan#6]
This is a useful projects. After I go through the code , got a question :
Why using two databases? What's the purpose ?   
We can store all of them in one database: more simple & user friendly

**Comment by Flynnon** [comment]
For the first question.
- Why we use mongodb ?
MongoDB is a schema less database so we can use it to store some schema mutable data(we think json is a great data format and in some cases we don't need full transaction). 
- Why we use mysql ?
Our management system is based on Django, so RDBMS is required for us, and mysql is easy to use, so we choose it。

For the second question.
It's not necessary to use mysql for storing rule-hit-log, although it's the simplest way for us. In fact, it's easy to choose a different database(mongodb, postgresql and so on..) to store it.
