### ISSUE TITLE
docker-compose 部署的时候 app_python_1这个镜像启动不了

### ISSUE THREAD

**Issue by Mingmingmew** [momosecurity/aswan#64]
报错 日志
![image](https://user-images.githubusercontent.com/16685324/104439886-9cf62b00-55cc-11eb-94d2-2396a1444702.png)

**Comment by Flynnon** [comment]
这里需要实现先启动数据源然后再启动APP，但是没找到docker-compose中怎么定义，因此只是简单的加了重试。理论上不会影响启动。
可以使用 ```docker-compose -f deploy/docker-compose.yaml ps``` 看看启动情况。
如果有解决这个问题的方法，欢迎回复并提交PR~
