### ISSUE TITLE
invalid source

### ISSUE THREAD

**Issue by huohuohahei** [momosecurity/aswan#7]
curl 127.0.0.1:50000/report/ -X POST -d '{"source": "test", "user_id": "10000", "ip": "127.0.0.1", "uid": "abcabc112333222"}' -H "Content-Type:application/json"
{"ec": 100, "error": "invalid source"}
什么原因啊

**Comment by Flynnon** [comment]
这个是由于此 `source` 未配置。
此处的 `source` 为 数据源配置 中的`配置名称key`项，可在`/config/source/list/`处进行配置。

**Comment by huohuohahei** [comment]
![image](https://user-images.githubusercontent.com/18340697/59815145-4ec66a80-934a-11e9-9307-c0e5e96fe21e.png)

已经配置数据源格式

curl 127.0.0.1:50000/report/ -X POST -d '{"source": "test", "user_id": "10000", "ip": "127.0.0.1", "uid": "abcabc112333222"}' -H "Content-Type:application/json"
{"ec": 100, "error": "invalid source"}

**Comment by Flynnon** [comment]
sorry，刚刚看了下，这个地方文档写错了，应该是  `source_name`。也就是：
``` bash
curl 127.0.0.1:50000/report/ -X POST -d '{"source_name": "test", "user_id": "10000", "ip": "127.0.0.1", "uid": "abcabc112333222"}' -H "Content-Type:application/json"
```
麻烦再试一下，后续我更新下文档。

**Comment by huohuohahei** [comment]
![image](https://user-images.githubusercontent.com/18340697/59816008-08263f80-934d-11e9-8d91-9cfeffd1eaf9.png)


curl 10.65.133.12:50000/report/ -X POST -d '{"source_name": "test", "user_id": "10000", "ip": "127.0.0.1", "uid": "abcabc112333222"}' -H "Content-Type:application/json"
{"ec": 100, "error": "invalid source"}

 curl 10.65.133.12:50000/report/ -X POST -d '{"source_name": "init_source_key", "user_id": "10000", "ip": "127.0.0.1", "uid": "abcabc112333222"}' -H "Content-Type:application/json"
{"ec": 101, "error": "invalid input"}

**Comment by huohuohahei** [comment]
1.发现只有使用内置数据源才可以访问通，新加的数据源无法访问；
2.按照默认规则访问后也无法输出相应的告警；
curl 10.65.133.12:50000/report/ -X POST -d '{"source_name": "init_source_key", "user_id": "111111", "ip": "1.1.1.1", "uid": "f3997ca02b4c0bd19a3dd9a8fa2b94e7","phone":"111","timestamp":1561004207}' -H "Content-Type:application/json"
{"result": "success", "ec": 0}

![image](https://user-images.githubusercontent.com/18340697/59818656-58a29a80-9357-11e9-809a-c2a5cee99ac2.png)

**Comment by Flynnon** [comment]
这里先简单介绍下风控系统数据源相关策略的设计思路，然后再解答上述问题

### 数据源

如wiki中所写的，与数据源相关的策略(限用户数型和时段频控型)需依赖业务方上报的数据，上报的数据被抽象为``数据源``，一个数据源配置所包含的元素如下:
``` 
配置名称key:  业务方上报数据时用来区分业务/场景的key，也就是业务方上报时的source_name
配置名称:  以一个好记的名称来标识此数据源
配置内容:  这一部分实际上是约束了业务方上报的数据格式(必须包含哪些字段，每个字段的值类型是什么)
```
### 上报接口( `/report/` )

此接口主要是供业务方在某些关键节点上报数据，以供后续的策略运算，其工作流如下
1. 接收到数据后，校验source_name参数是否传递，并校验其对应的数据源是否存在，校验不通过则返回错误(即上面的 "invalid source")
2. 校验上报数据格式与数据源中的配置是否匹配，不匹配则返回错误
3. 扫描现有的有效规则，查看那些策略使用了这份数据源，然后对每个策略分别执行 ``抽取 -> 转化 -> 清洗 -> 存储`` 来将数据存储下来(此处可能存储多份数据)，最后返回结果

### 查询接口( `/query/` )

此接口主要是在某些关键操作前判定其是否合法，再由业务方对操作进行干预，其工作流如下
1. 对rule_id参数进行校验(参数是否正确上传、规则是否存在、当前是否有效等等), 若rule_id不合法，直接返回错误
2. 通过rule_id拿到所要执行的策略组，然后按照权重大小分别执行，并记录拦截日志，最后将第一个命中的策略原子组信息返回，若均无命中，则返回默认返回值

## 解答

- 发现只有使用内置数据源才可以访问通，新加的数据源无法访问
对于未被策略引用的数据源，我们认为它是不存在/无效的，因此此数据源在校验是会被判定为不合法

- 按照默认规则访问后也无法输出相应的告警
一直访问report接口，当然不会有是否命中规则的返回值，也不会有拦截日志
