### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by huohuohahei** [momosecurity/aswan#8]
现在搭建了一套系统也运行起来了，请问外部数据如何使用aswa建立的规则？

**Comment by Flynnon** [comment]
可以说的具体一些么?什么是``外部数据使用aswan建立的规则``?

aswan系统是通过 report 和 query 两个接口来与业务侧进行交互的，扩展/特殊参数都可以放到请求体中，由系统进行处理。

**Comment by huohuohahei** [comment]
假设我的数据是
{"user_id": "111111", "ip": "1.1.1.1", "uid": "f3997ca02b4c0bd19a3dd9a8fa2b94e7","phone":"111","timestamp":1561004207}
如果想判断这个数据是不是触发了某种规则，比如ip是不是在黑名单里，先配置数据源init_source_key，然后通过rest接口方式访问系统：
curl ip:50000/report/ -X POST -d '{"source_name": "init_source_key", "user_id": "111111", "ip": "1.1.1.1", "uid": "f3997ca02b4c0bd19a3dd9a8fa2b94e7","phone":"111","timestamp":1561004207}' -H "Content-Type:application/json"
返回值{"result": "success", "ec": 0} 代表该数据没有触发相应的规则？？

**Comment by myisjon** [comment]
query才是判断这条数据是否触发规则，report上报用户行为的结果，用于策略的计算。

**Comment by huohuohahei** [comment]
按照系统内置的规则，采用以下访问应该是被拦截的吧？为何结果是pass？
curl ip:50000/query/ -X POST -d '{"rule_id": "1", "user_id": "111111"}' -H "Content-Type:application/json"
{"result": {"control": "pass", "weight": 0}, "ec": 0}

![image](https://user-images.githubusercontent.com/18340697/60558075-7d950580-9d7a-11e9-872c-7a7379dcde27.png)

**Comment by Flynnon** [comment]
初始规则的名单策略部分如下:
![规则1部分截图](https://user-images.githubusercontent.com/10295015/60559493-1ded2900-9d7f-11e9-91e6-4cb3777097a4.png)

这个策略组是由三个名单策略组成的，他们之间是且的关系，也就是只有同时命中这三条规则才会命中这个策略组。

而上述请求post方法时，使用的参数不全，因此未能命中此策略组。

**Comment by huohuohahei** [comment]
谢谢您的耐心回答，经过测试确实是且的关系；
1.一条数据先经过query接口访问，根据结果确认是否触发某个规则；
2.如果是异常数据就将这条数据经过report接口上报？？上报的结果在MongoDB中？？您上面提到的report上报用户行为的结果，用于策略的计算。能具体一点吗？

**Comment by Flynnon** [comment]
### aswan规则引擎的工作流

1. 业务方在用户执行前调用 query 接口来判定当前行为是否合法，不合法则转向2，合法则转向3；
2. 用户动作被拦截，结束；
3. 执行业务侧逻辑，若最终用户成功转向4，否则转向5；
4. 风控系统存在数据源相关的策略则调用 report 接口来上报结果供引擎后续计算，转向5；
5. 直接结束。

### 例子

现在有一个打地鼠的活动，打地鼠成功可获得小礼物一个

#### 规则

业务侧规则为：
1. 用户每次打地鼠有10%的概率成功

风控侧规则为：
1. 异常用户不能打地鼠 --> deny
2. 同uid上30分钟内限1次 --> deny

#### 请求示例

以一个正常用户极短时间内执行三次动作来举例:
第一次：用户打地鼠前，调用query接口，由于未命中策略，得到pass，用户用户运气不错，打地鼠成功，则调用report上报数据；
第二次：用户打地鼠前，调用query接口，由于未命中策略，得到pass，由于用户运气不好，打地鼠失败，则直接结束；
第三次：用户打地鼠前，调用query接口，由于未命中策略，得到pass，由于用户运气不错，打地鼠成功，则调用report上报数据；
第四次：用户打地鼠前，调用query接口，命中时段频控型策略，得到deny，此次行为被拦截，用户打地鼠失败，结束。

**Comment by Flynnon** [comment]
目前aswan系统依赖数据源及作用如下：

- mysql:
    Django自带的部分模块(认证、用户等等)、拦截日志、审计日志
- mongo:
    存储名单(备份/后端展示)、权限部分
- redis
    各种配置项(规则配置、策略配置、数据源配置等等)，上报数据记录、拦截日志传输(为了性能不会直接写mysql，使用redis队列作为中间层)

**Comment by huohuohahei** [comment]
明白了，非常感谢您的耐心回答，解答了我很多疑惑，谢谢！！！
